In [13]:
import math
import numpy as np

lower = np.zeros(shape=(5, 5))
upper = np.zeros(shape=(5, 5))
matrix = np.array([[14, 14, -9, 3, -5], [15, 52, -15, 2, -32], [-9, -15, 36, -5, 16], [3, 2, -5, 47, 49], [-5, -32, 16, 49, 79]])

# Performs LU decomposition
for i in range(5):
    # U matrix
    for k in range(i, 5):
        sum = 0
        for j in range(0, i):
            sum += lower[i][j]*upper[j][k]
        upper[i][k] = matrix[i][k] - sum

    # L matrix
    for k in range(i, 5):
        if i == k:
            lower[i][i] = 1
        else:
            sum = 0
            for j in range(i):
                sum += lower[k][j]*upper[j][i]
            lower[k][i] = (matrix[k][i] - sum) / upper[i][i]
print(matrix)
print(upper)
print(lower)

for row in range(5):
    for col in range(5):
        matrix[row][col] = math.floor(matrix[row][col])
        upper[row][col] = math.floor(upper[row][col])
        lower[row][col] = math.floor(lower[row][col])

print(matrix)
print(upper)
print(lower)



[[ 14  14  -9   3  -5]
 [ 15  52 -15   2 -32]
 [ -9 -15  36  -5  16]
 [  3   2  -5  47  49]
 [ -5 -32  16  49  79]]
[[ 14.          14.          -9.           3.          -5.        ]
 [  0.          37.          -5.35714286  -1.21428571 -26.64285714]
 [  0.           0.          29.34555985  -3.26833977   8.46525097]
 [  0.           0.           0.          45.96612065  50.27912637]
 [  0.           0.           0.           0.           0.32986943]]
[[ 1.          0.          0.          0.          0.        ]
 [ 1.07142857  1.          0.          0.          0.        ]
 [-0.64285714 -0.16216216  1.          0.          0.        ]
 [ 0.21428571 -0.02702703 -0.10959805  1.          0.        ]
 [-0.35714286 -0.72972973  0.3024801   1.09154167  1.        ]]
[[ 14  14  -9   3  -5]
 [ 15  52 -15   2 -32]
 [ -9 -15  36  -5  16]
 [  3   2  -5  47  49]
 [ -5 -32  16  49  79]]
[[ 14.  14.  -9.   3.  -5.]
 [  0.  37.  -6.  -2. -27.]
 [  0.   0.  29.  -4.   8.]
 [  0.   0.   0.  45.  50.]